<?php

namespace PN\Bundle\CMSBundle\Repository;

use PN\Bundle\CMSBundle\Entity\Blog;
use PN\Utils\SQL;
use PN\Utils\Validate;

/**
 * BlogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BlogRepository extends \Doctrine\ORM\EntityRepository
{

    public function findOneBySlug($slug)
    {
        $blog = new Blog();
        $connection = $this->getEntityManager();
        $seoBaseRoute = $connection->getRepository('SeoBundle:SeoBaseRoute')->findByEntity($blog);
        $entity = $connection->getRepository('SeoBundle:Seo')->findOneBySlugAndBaseRoute($slug, $seoBaseRoute->getId());
        if ($entity) {
            return $entity->getBlog();
        } else {
            return NULL;
        }
    }

    public function filter($search, $count = FALSE, $startLimit = NULL, $endLimit = NULL)
    {

        $sortSQL = [
            0 => 'b.title',
            1 => 'b.reference',
            2 => 'b.publish',
            3 => 'b.created',
            4 => 'RAND()'
        ];


        $connection = $this->getEntityManager();

        $where = FALSE;
        $clause = '';

        $searchFiltered = new \stdClass();


        foreach ($search as $key => $value) {
            if (Validate::not_null($value) AND !is_array($value)) {
                $searchFiltered->{$key} = substr($connection->getConnection()->quote($value), 1, -1);
            } else {
                $searchFiltered->{$key} = $value;
            }
        }

        if (isset($searchFiltered->blogId) AND Validate::not_null($searchFiltered->blogId)) {
            $where = ($where) ? " AND " : " WHERE ";
            $clause .= $where . " b.id != $searchFiltered->blogId ";

        }

        if (isset($searchFiltered->deleted) AND in_array($searchFiltered->deleted, array(0, 1))) {
            $where = ($where) ? " AND " : " WHERE ";
            if ($searchFiltered->deleted == 1) {
                $clause .= $where . " b.deleted IS NOT NULL ";
            } else {
                $clause .= $where . " b.deleted IS NULL ";
            }
        }

        if (isset($searchFiltered->publish) AND in_array($searchFiltered->publish, array(0, 1))) {
            $where = ($where) ? " AND " : " WHERE ";
            $clause .= $where . " b.publish = $searchFiltered->publish ";

        }

        if (isset($searchFiltered->category) AND Validate::not_null($searchFiltered->category)) {
            $where = ($where) ? " AND " : " WHERE ";
            $clause .= $where . " b.blog_category_id = $searchFiltered->category ";

        }

        if (isset($searchFiltered->string) AND $searchFiltered->string) {

            if (SQL::validateSS($searchFiltered->string)) {
                $where = ($where) ? ' AND ( ' : ' WHERE ( ';
                $clause .= SQL::searchSCG($searchFiltered->string, 'b.id', $where);
                $clause .= SQL::searchSCG($searchFiltered->string, 'b.title', ' OR ');
                $clause .= " ) ";
            }
        }


        if ($count) {
            $sqlInner = "SELECT COUNT(b.id) as count FROM blog b ";
            $sqlInner .= $clause;

            $statement = $connection->getConnection()->prepare($sqlInner);
            $statement->execute();
            $queryResult = $statement->fetch();

            return (int)$queryResult['count'];
        }


        $sql = "SELECT b.id FROM blog b ";
        $sql .= $clause;


        if (isset($searchFiltered->ordr) AND Validate::not_null($searchFiltered->ordr)) {
            $dir = $searchFiltered->ordr['dir'];
            $columnNumber = $searchFiltered->ordr['column'];
            if (isset($columnNumber) AND array_key_exists($columnNumber, $sortSQL)) {
                $sql .= " ORDER BY " . $sortSQL[$columnNumber] . " $dir";
            }
        } else {
            $sql .= ' ORDER BY b.id DESC';
        }

        if ($startLimit !== NULL AND $endLimit !== NULL) {
            $sql .= " LIMIT " . $startLimit . ", " . $endLimit;
        }

        $statement = $connection->getConnection()->prepare($sql);
        $statement->execute();
        $filterResult = $statement->fetchAll();
        $result = array();
        foreach ($filterResult as $key => $r) {
            $result[] = $this->find($r['id']);
        }
        return $result;
    }

}
