<?php

namespace PN\Bundle\CMSBundle\Repository;
use PN\Utils\SQL;
use PN\Utils\Validate;

/**
 * BloggerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BloggerRepository extends \Doctrine\ORM\EntityRepository
{
    public function filter($search, $count = FALSE, $startLimit = NULL, $endLimit = NULL) {

        $sortSQL = [
            0 => 'b.id',
            1 => 'b.title',
            2 => 'b.created'
        ];


        $connection = $this->getEntityManager();

        $where = FALSE;
        $clause = '';

        $searchFiltered = new \stdClass();

        foreach ($search as $key => $value) {
            if (Validate::not_null($value) AND ! is_array($value)) {
                $searchFiltered->{$key} = substr($connection->getConnection()->quote($value), 1, -1);
            } else {
                $searchFiltered->{$key} = $value;
            }
        }

        if (isset($searchFiltered->deleted) AND in_array($searchFiltered->deleted, array(0, 1))) {
            $where = ($where) ? " AND " : " WHERE ";
            if ($searchFiltered->deleted == 1) {
                $clause .= $where . " b.deleted IS NOT NULL ";
            } else {
                $clause .= $where . " b.deleted IS NULL ";
            }
        }

        if (isset($searchFiltered->string) AND $searchFiltered->string) {

            if (SQL::validateSS($searchFiltered->string)) {
                $where = ($where) ? ' AND ( ' : ' WHERE ( ';
                $clause .= SQL::searchSCG($searchFiltered->string, 'b.id', $where);
                $clause .= SQL::searchSCG($searchFiltered->string, 'b.title', ' OR ');
                $clause .= " ) ";
            }
        }


        if ($count) {
            $sqlInner = "SELECT COUNT(b.id) as count FROM blogger b " ;
            $sqlInner .= $clause;

            $statement = $connection->getConnection()->prepare($sqlInner);
            $statement->execute();
            $queryResult = $statement->fetch();

            return (int) $queryResult['count'];
        }


        $sql = "SELECT b.id FROM blogger b ";
        $sql .= $clause;


        if (isset($searchFiltered->ordr) AND Validate::not_null($searchFiltered->ordr)) {
            $dir = $searchFiltered->ordr['dir'];
            $columnNumber = $searchFiltered->ordr['column'];
            if (isset($columnNumber) AND array_key_exists($columnNumber, $sortSQL)) {
                $sql .= " ORDER BY " . $sortSQL[$columnNumber] . " $dir";
            }
        } else {
            $sql .= ' ORDER BY s.id DESC';
        }

        if ($startLimit !== NULL AND $endLimit !== NULL) {
            $sql .= " LIMIT " . $startLimit . ", " . $endLimit;
        }

        $statement = $connection->getConnection()->prepare($sql);
        $statement->execute();
        $filterResult = $statement->fetchAll();
        $result = array();
        foreach ($filterResult as $key => $r) {
            $object = $connection->getRepository('CMSBundle:Blogger')->find($r['id']);
            $result[] = $object;
        }
        return $result;
    }

}
