<?php

namespace PN\Bundle\CMSBundle\Repository;
use PN\Bundle\CMSBundle\Entity\BlogCategory;
use PN\Utils\SQL;
use PN\Utils\Validate;

/**
 * BlogCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BlogCategoryRepository extends \Doctrine\ORM\EntityRepository
{
    public function findOneBySlug($slug)
    {
        $blogCategory = new BlogCategory();
        $connection = $this->getEntityManager();
        $seoBaseRoute = $connection->getRepository('SeoBundle:SeoBaseRoute')->findByEntity($blogCategory);
        $entity = $connection->getRepository('SeoBundle:Seo')->findOneBySlugAndBaseRoute($slug, $seoBaseRoute->getId());
        if ($entity) {
            return $entity->getBlogCategory();
        } else {
            return NULL;
        }
    }

    public function findAll()
    {
        return $this->findBy(['deleted'=>NULL]);
    }


    public function filter($search, $count = FALSE, $startLimit = NULL, $endLimit = NULL) {

        $sortSQL = [
            0 => 'bc.title',
            1 => 'bc.created',
        ];
        $connection = $this->getEntityManager()->getConnection();
        $where = FALSE;
        $clause = '';

        $searchFiltered = new \stdClass();
        foreach ($search as $key => $value) {
            if (Validate::not_null($value) AND ! is_array($value)) {
                $searchFiltered->{$key} = substr($connection->quote($value), 1, -1);
            }
            else{
                $searchFiltered->{$key} = $value;
            }
        }

        if (isset($searchFiltered->deleted) AND in_array($searchFiltered->deleted, array(0, 1))) {
            $where = ($where) ? " AND " : " WHERE ";
            if ($searchFiltered->deleted == 1) {
                $clause .= $where . " bc.deleted IS NOT NULL ";
            } else {
                $clause .= $where . " bc.deleted IS NULL ";
            }
        }
        if (isset( $searchFiltered->string) AND  $searchFiltered->string) {

            if (SQL::validateSS( $searchFiltered->string)) {
                $where = ($where) ? ' AND ( ' : ' WHERE ( ';
                $clause .= SQL::searchSCG( $searchFiltered->string, 'bc.id', $where);
                $clause .= SQL::searchSCG( $searchFiltered->string, 'bc.title', ' OR ');
                $clause.= " ) ";
            }
        }

        if ($count) {
            $sqlInner = "SELECT count(bc.id) as `count` FROM blog_category bc ";

            $statement = $connection->prepare($sqlInner);
            $statement->execute();
            return $queryResult = $statement->fetchColumn();
        }
//----------------------------------------------------------------------------------------------------------------------------------------------------
        $sql = "SELECT bc.id FROM blog_category bc ";
        $sql .= $clause;

        if (isset($searchFiltered->ordr) AND Validate::not_null($searchFiltered->ordr)) {
            $dir = $searchFiltered->ordr['dir'];
            $columnNumber = $searchFiltered->ordr['column'];
            if (isset($columnNumber) AND array_key_exists($columnNumber, $sortSQL)) {
                $sql .= " ORDER BY " . $sortSQL[$columnNumber] . " $dir";
            }
        } else {
            $sql .= ' ORDER BY bc.id DESC';
        }


        if ($startLimit !== NULL AND $endLimit !== NULL) {
            $sql .= " LIMIT " . $startLimit . ", " . $endLimit;
        }

        $statement = $connection->prepare($sql);
        $statement->execute();
        $filterResult = $statement->fetchAll();
        $result = array();

        foreach ($filterResult as $key => $r) {
            $result[] = $this->find($r['id']);
        }
//-----------------------------------------------------------------------------------------------------------------------
        return $result;
    }
}
