<?php

namespace PN\Bundle\CMSBundle\Repository;
use PN\Utils\SQL;
use PN\Utils\Validate;

/**
 * BloggerTagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BloggerTagRepository extends \Doctrine\ORM\EntityRepository
{

    public function filter($search, $count = FALSE, $startLimit = NULL, $endLimit = NULL) {

        $sortSQL = [
            0 => 'bt.id',
            1 => 'bt.title',
            2 => 'bt.created',
        ];
        $connection = $this->getEntityManager()->getConnection();
        $where = FALSE;
        $clause = '';

        $searchFiltered = new \stdClass();
        foreach ($search as $key => $value) {
            if (Validate::not_null($value) AND ! is_array($value)) {
                $searchFiltered->{$key} = substr($connection->quote($value), 1, -1);
            }
            else{
                $searchFiltered->{$key} = $value;
            }
        }

        if (isset($searchFiltered->deleted) AND in_array($searchFiltered->deleted, array(0, 1))) {
            $where = ($where) ? " AND " : " WHERE ";
            if ($searchFiltered->deleted == 1) {
                $clause .= $where . " bt.deleted IS NOT NULL ";
            } else {
                $clause .= $where . " bt.deleted IS NULL ";
            }
        }
        if (isset( $searchFiltered->string) AND  $searchFiltered->string) {

            if (SQL::validateSS( $searchFiltered->string)) {
                $where = ($where) ? ' AND ( ' : ' WHERE ( ';
                $clause .= SQL::searchSCG( $searchFiltered->string, 'bt.id', $where);
                $clause .= SQL::searchSCG( $searchFiltered->string, 'bt.title', ' OR ');
                $clause.= " ) ";
            }
        }

        if ($count) {
            $sqlInner = "SELECT count(bt.id) as `count` FROM blogger_tag bt ";

            $statement = $connection->prepare($sqlInner);
            $statement->execute();
            return $queryResult = $statement->fetchColumn();
        }
//----------------------------------------------------------------------------------------------------------------------------------------------------
        $sql = "SELECT bt.id FROM blogger_tag bt ";
        $sql .= $clause;

        if (isset($searchFiltered->ordr) AND Validate::not_null($searchFiltered->ordr)) {
            $dir = $searchFiltered->ordr['dir'];
            $columnNumber = $searchFiltered->ordr['column'];
            if (isset($columnNumber) AND array_key_exists($columnNumber, $sortSQL)) {
                $sql .= " ORDER BY " . $sortSQL[$columnNumber] . " $dir";
            }
        } else {
            $sql .= ' ORDER BY bt.id DESC';
        }


        if ($startLimit !== NULL AND $endLimit !== NULL) {
            $sql .= " LIMIT " . $startLimit . ", " . $endLimit;
        }

        $statement = $connection->prepare($sql);
        $statement->execute();
        $filterResult = $statement->fetchAll();
        $result = array();

        foreach ($filterResult as $key => $r) {
            $result[] = $this->getEntityManager()->getRepository('CMSBundle:BloggerTag')->find($r['id']);
        }
//-----------------------------------------------------------------------------------------------------------------------
        return $result;
    }
}
